version: '3.8'

services:

  postgresql:
    image: postgres
    ports:
      - 5433:5432
    environment:
        - POSTGRES_PASSWORD=postgres

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rmquser
      - RABBITMQ_DEFAULT_PASS=abcd1234

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 4317:4317
      - 16686:16686
    environment:
        - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
        - COLLECTOR_OTLP_ENABLED=true

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000