global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets: ['localhost:9090']
  - job_name: customers-ms
    metrics_path: '/customers-ms/actuator/prometheus'
    static_configs:
    - targets: ['192.168.68.107:8090']
  - job_name: cart-ms
    metrics_path: '/cart-ms/actuator/prometheus'
    static_configs:
    - targets: ['192.168.68.107:8090']
  - job_name: payment-ms
    metrics_path: '/payment-ms/actuator/prometheus'
    static_configs:
    - targets: ['192.168.68.107:8090']